// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDVQopgjGM2gTtywAJ5C2eH36eeqRPZ4',
    appId: '1:601842383699:web:43c979b50d152a3d27ffa6',
    messagingSenderId: '601842383699',
    projectId: 'pingo-cd60b',
    authDomain: 'pingo-cd60b.firebaseapp.com',
    storageBucket: 'pingo-cd60b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVxsLJbvU7GJJlQ1RPWlOoLPx3PHYbqr8',
    appId: '1:601842383699:android:f32868d42346e50927ffa6',
    messagingSenderId: '601842383699',
    projectId: 'pingo-cd60b',
    storageBucket: 'pingo-cd60b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTNiHohFhn6T8-sCE34FJ3bXzxTfMZfR0',
    appId: '1:601842383699:ios:d379d325353d85bf27ffa6',
    messagingSenderId: '601842383699',
    projectId: 'pingo-cd60b',
    storageBucket: 'pingo-cd60b.appspot.com',
    iosClientId: '601842383699-d1cr3rfus83f62gjuub879oe48p6o1a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rajafsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTNiHohFhn6T8-sCE34FJ3bXzxTfMZfR0',
    appId: '1:601842383699:ios:16e89453ed5308f227ffa6',
    messagingSenderId: '601842383699',
    projectId: 'pingo-cd60b',
    storageBucket: 'pingo-cd60b.appspot.com',
    iosClientId: '601842383699-0ld7pjms4468r2ep5i2pdvf01910ad09.apps.googleusercontent.com',
    iosBundleId: 'com.example.rajafsg.RunnerTests',
  );
}
